version: 1.2
workflows:
  - name: FilterVcf
    subclass: WDL
    primaryDescriptorPath: /wdl/filter_vcf_PASS_DEL_AF0.05_DoubleEvidence.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
